
### Practice - List of Marks


### Question 1  :

**a)**    Write a Python program that accepts a list of marks then prints the letter grade and description according to the [Grading System](https://continuing.ryerson.ca/contentManagement.do?method=load&code=CM000034) of the Chang School of Continuing Education.

For example, if the user enters `90, 120, -12, 71.5, 62.5`, the output would be as follows:

| Mark | Letter Grade | Performance Description |
|:-:|:-:|:-:|
| 90 | A+ | Excellent |
| 120 | Not Possible | Not Possible |
| -12 | Not Possible | Not Possible |
| 71.5 | B- | Good |
| 62.5 | C | Satisfactory |

In [1]:

# List of marks for the user to enter
listMarks = list(map(float, input("Enter the marks separated by a comma:\n").split(",")))
print() # print a new line

#print headers
print("Marks\tLetter Grade\tPerformance Description")
print("-"*48) # print a line that separates the headers

# List of Marks
for x in listMarks:
    print(x, end=" ")
    if 100>= x >= 89.5: 
        print("\tA+\t\tExcellent")
    elif 89.5> x >= 84.5:  
        print("\tA\t\tExcellent")
    elif 84.5> x >= 79.5:
        print("\tA-\t\tExcellent")
    elif 79.5> x >= 76.5:
        print("\tB+\t\tGood")
    elif 76.5> x >= 72.5:
        print("\tB\t\tGood")
    elif 72.5> x >= 69.5:
        print("\tB-\t\tGood")
    elif 69.5> x >= 66.5:
        print("\tC+\t\tSatisfactory")
    elif 66.5> x >= 62.5:
        print("\tC\t\tSatisfactory")
    elif 62.5> x >= 59.5:
        print("\tC-\t\tSatisfactory")
    elif 59.5> x >= 56.5:
        print("\tD+\t\tMarginal")
    elif 56.5> x >= 52.5:
        print("\tD\t\tMarginal")
    elif 52.5> x >= 49.5:
        print("\tD-\t\tMarginal")
    elif 49.5> x >= 0:
        print("\tF\t\tUnsatisfactory")     
    else:
        print("\tNot Possible\tNot Possible")

Enter the marks separated by a comma:
90, 120, -12, 71.5, 62.5

Marks	Letter Grade	Performance Description
------------------------------------------------
90.0 	A+		Excellent
120.0 	Not Possible	Not Possible
-12.0 	Not Possible	Not Possible
71.5 	B-		Good
62.5 	C		Satisfactory


**b)**  Write a code to compute and print the sum of squares of only the `Excellent` marks.

For example, if the user enters `90.5, 120, -12, 71.3, 82.2, 62.5`, then the output should be: <br>
`The Excellent marks are:  [90.5, 82.2]`<br>
`The sum of squares is  14947.09`

In [6]:
# List of marks for the user to enter
listMarks = list(map(float, input("Enter the marks separated by a comma:\n").split(",")))
print() # print a new line

# print headers 
print("Marks\tLetter Grade\tPerformance Description")
print("-"*48) # print a line that separates the headers

Excelmarks=[] # empty array for Excellent marks

# List of Marks
for x in listMarks:
    print(x, end=" ")
    if 100>= x >= 89.5: 
        print("\tA+\t\tExcellent")
        Excelmarks.append(x) #append the Excellent marks
    elif 89.5> x >= 84.5:  
        print("\tA\t\tExcellent")
        Excelmarks.append(x) #append the Excellent marks
    elif 84.5> x >= 79.5:
        print("\tA-\t\tExcellent")
        Excelmarks.append(x) #append the Excellent marks
    elif 79.5> x >= 76.5:
        print("\tB+\t\tGood")
    elif 76.5> x >= 72.5:
        print("\tB\t\tGood")
    elif 72.5> x >= 69.5:
        print("\tB-\t\tGood")
    elif 69.5> x >= 66.5:
        print("\tC+\t\tSatisfactory")
    elif 66.5> x >= 62.5:
        print("\tC\t\tSatisfactory")
    elif 62.5> x >= 59.5:
        print("\tC-\t\tSatisfactory")
    elif 59.5> x >= 56.5:
        print("\tD+\t\tMarginal")
    elif 56.5> x >= 52.5:
        print("\tD\t\tMarginal")
    elif 52.5> x >= 49.5:
        print("\tD-\t\tMarginal")
    elif 49.5> x >= 0:
        print("\tF\t\tUnsatisfactory")     
    else:
        print("\tNot Possible\tNot Possible")
# print Excellent marks
print("\nThe Excellent marks are:", Excelmarks)
# print the sum of squares using sum(map(lambda()))
print("The sum of squares is", sum(map(lambda x:x*x, Excelmarks)))

Enter the marks separated by a comma:
 90.5, 120, -12, 71.3, 82.2, 62.5



Marks	Letter Grade	Performance Description
------------------------------------------------
90.5 	A+		Excellent
120.0 	Not Possible	Not Possible
-12.0 	Not Possible	Not Possible
71.3 	B-		Good
82.2 	A-		Excellent
62.5 	C		Satisfactory

The Excellent marks are: [90.5, 82.2]
The sum of squares is 14947.09


**c)**  Write a code to compute and print the `Median`, `Average` and `Mode` of the marks between 0 and 100, inclusively, after rounding each mark to the nearest integer.  Ensure notifying the user if there is no unique mode found, as the `Mode` in this exercise returns only the single most common mark in the list.

For example, if the user enters `89.7, 120, -12, 90, 60.2`, then the output should be: <br>
`The valid marks are:  [90, 90, 60] `<br>
`Median is 90 ; Average is 80 ; Mode is 90`

However, if the user enters `90.6, 70, 100, 40.4`, then the output should be: <br>
`The valid marks are:  [91, 70, 100, 40] `<br>
`Median is 80.5 ; Average is 75.25 ; No unique mode found`

Also, if the user enters `65, 65, 65, 35, 35, 35`, then the output should be: <br>
`The valid marks are:  [65, 65, 65, 35, 35, 35] `<br>
`Median is 50.0 ; Average is 50 ; No unique mode found`

Hint: Use the [statistics] (https://docs.python.org/3.7/library/statistics.html) module as it provides functions to calculate mathematical statistics of numeric data.

In [8]:
# List of marks for the user to enter
listMarks = list(map(float, input("Enter the marks separated by a comma:\n").split(",")))
print() # print a new line

# Round the marks to the nearest integer and filter for valid marks
markStat = list(map(round, listMarks))
markStat = list(filter(lambda x: 100 >= x >= 0, markStat))
print("The valid marks are: ", markStat)

import statistics
# Print the Median
Median = print("Median is ", statistics.median(markStat))
# Print the Average
Average = print("Average is ", statistics.mean(markStat))

# Print the mode. When there is not a unique mode, it raise an exception
try: 
    mode= statistics.mode(markStat) # find the mode
    print("Mode is ", mode)
except:   # if there's statisticsError then print
    print("No unique mode found") 

Enter the marks separated by a comma:
 89.7, 120, -12, 90, 60.2



The valid marks are:  [90, 90, 60]
Median is  90
Average is  80
Mode is  90


*****